### ISSUE TITLE
tplot crashes on variable created via tplot_restore

### ISSUE THREAD

**Issue by jameswilburlewis** [MAVENSDC/PyTplot#167]
It looks like tplot_restore sometimes creates string-valued metadata values as bytes rather than strings.   Then when tplot tries to perform string operations on them, it crashes:

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\unittest\suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "C:\Users\james\PycharmProjects\pyspedas_spinmodel_github\pyspedas\analysis\tests\test_twavpol.py", line 46, in setUpClass
    pytplot.tplot('thc_scf_fac')
  File "C:\Users\james\PycharmProjects\pyspedas_spinmodel_github\venv\lib\site-packages\pytplot\tplot.py", line 160, in tplot
    return mpl_tplot(name, var_label=var_label,
  File "C:\Users\james\PycharmProjects\pyspedas_spinmodel_github\venv\lib\site-packages\pytplot\MPLPlotter\tplot.py", line 302, in tplot
    this_axis.set_ylabel(ytitle + '\n' + ysubtitle, fontsize=char_size, color=ytitle_color)
TypeError: can't concat str to bytes

```

Test file to reproduce: [http://spedas.org/testfiles/thc_twavpol_validate.tplot](http://spedas.org/testfiles/thc_twavpol_validate.tplot)

Procedure: 

1. Download the test file
2. Pass it to tplot restore
3. Use get_data to get the metadata attributes for the variable 'thc_scf_fac', note that the ytitle attributes is not a string
4. Call tplot on thc_scf_fac and see how it fails when creating the Y axis label.

The other variables in this tplot save file seem ok.  It's a bit weird that the other string-valued attributes are correctly treated as strings, even on the affected tplot variable.

The example file was created using IDL 8.5.1 on Windows 10.  The crash occurs on Windows 10, using Python 3.10.1, with pytplot version pytplot_mpl_temp-2.1.14

**Comment by jameswilburlewis** [comment]
Fixed in pytplot-mpl-temp 2.1.19
