### ISSUE TITLE
tplot_restore does not restore 'data_att' field from limits structure

### ISSUE THREAD

**Issue by jameswilburlewis** [MAVENSDC/PyTplot#174]
Test file at https://spedas.org/testfiles/data_att_test.tplot

This file contains a single tplot variable, 'tha_state_pos'.   Using tplot_restore on IDL gives the usual structures in the dlimits:

```
THEMIS> get_data,'tha_state_pos',data=d,dl=dl
THEMIS> help,dl
** Structure <21e95330>, 7 tags, length=848, data length=836, refs=2:
   CDF             STRUCT    -> <Anonymous> Array[1]
   SPEC            BYTE         0
   LOG             BYTE         0
   DATA_ATT        STRUCT    -> <Anonymous> Array[1]
   COLORS          INT       Array[3]
   LABELS          STRING    Array[3]
   YSUBTITLE       STRING    '[km]'
THEMIS> help,dl.data_att
** Structure <21ea3c50>, 3 tags, length=48, data length=48, refs=2:
   COORD_SYS       STRING    'gei'
   ST_TYPE         STRING    'pos'
   UNITS           STRING    'km'
```

pytplot.tplot_restore() produces a tplot variable whose metadata dictionary only contains 'plot_options' as a top level key, and the data_att values don't seem to be in any of the substructures.

```
pytplot.tplot_restore("C:/Users/james/data_att_test.tplot")
pytplot.tplot_names()
0 : tha_state_pos
['tha_state_pos']

meta=pytplot.get_data('tha_state_pos',metadata=True)
meta
{'plot_options': {'xaxis_opt': {'axis_label': 'Time', 'crosshair': 'X', 'x_axis_type': 'linear'}, 'yaxis_opt': {'axis_label': '', 'crosshair': 'Y', 'y_axis_type': 'linear', 'y_range': [-46907.03, 86018.85], 'legend_names': ['x', 'y', 'z'], 'axis_subtitle': '[km]'}, 'zaxis_opt': {'axis_label': 'tha_state_pos', 'crosshair': 'Z', 'z_axis_type': 'linear'}, 'line_opt': {}, 'trange': [1174608000.0, 1174694340.0], 'time_bar': [], 'extras': {'panel_size': 1, 'border': True, 'spec': 0, 'alt': 0, 'map': 0, 'plotter': None, 'spec_dim_to_plot': 'v'}, 'create_time': 1680642893.492, 'links': {}, 'spec_bins_ascending': True, 'overplots': [], 'interactive_xaxis_opt': {}, 'interactive_yaxis_opt': {}, 'error': None}}

meta['data_att']
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
KeyError: 'data_att'
```

It would be especially useful for writing unit tests, to be able to call cotrans_get_coord() on variables created via tplot_restore().

```

**Comment by supervised** [comment]
I'm getting an error on the test file:

> Not Found
> The requested URL was not found on this server.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by jameswilburlewis** [comment]
Sorry, I mistyped the URL.  It's https://spedas.org/testfiles/data_att_test.tplot (test, not testfile).

**Comment by ericthewizard** [comment]
This one should be fixed in the bleeding edge now
